### ISSUE TITLE
old_film.sh: 58: old_film.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by shayzalman** [mazurkin/mkfilm_old#1]
Hi
thanks for the great script 
Im running the bash script and get the following error (on Debian 3.16.7-ckt20-1+deb8u3)
old_film.sh: 58: old_film.sh: Syntax error: "(" unexpected

$FFMPEG -f concat -i **<(yes** "file '${WRK_DIR}/build/noise.mp4'" | head -n 1000) -y -t ${DURATION} \

Is the <(yes syntax necessary?

Thanks

**Comment by mazurkin** [comment]
Hi, yes, it's required

`<(yes "file '${WRK_DIR}/build/noise.mp4'" | head -n 1000)`

makes a temporary file with 1000 repeats of string "file '${WRK_DIR}/build/noise.mp4'" and puts file name as an argument. it's called https://en.wikipedia.org/wiki/Process_substitution

my bash version (Xubuntu 14.04) is 

```
$ dpkg -s bash | grep -i version
Version: 4.3-7ubuntu1.5
```

Sorry, the script is just a rough sample not a final product

**Comment by shayzalman** [comment]
Hi Nickolay

Do you have any other cool FFMPEG effects like this old film that you have
published?

Thanks

On Tue, May 17, 2016 at 4:58 PM, Nickolay Mazurkin <notifications@github.com

**Comment by mazurkin** [comment]
No any others, sorry. I had some ideas but didn't realized.
